kind: ConfigMap
apiVersion: v1
data:
  prometheus-config: |-
    scrape_configs:
    - job_name: example-app
      scrape_interval: 30s
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app, __meta_kubernetes_pod_labelpresent_app]
        separator: ;
        regex: (example-app);true
        action: keep
      - source_labels: [__meta_kubernetes_pod_container_port_name]
        regex: metrics
        action: keep
     - source_labels: [__meta_kubernetes_pod_label_app]
       action: replace
       target_label: app
metadata:
  name: ama-metrics-prometheus-config
  namespace: kube-system
